### PR TITLE
Update Kubernetes to v1.29.3

### PR DESCRIPTION
**Pull request by AliPiccioniQC**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
This probably fails due to a go signature error. Add

```
build:
  binary_relocation: false
```

to the `-node` output.

**Comment by dhirschfeld** [comment]
Thanks for fixing the build! It looks good, but what's with the addition of the `recipe-scripts-license.txt` file?

Kubernetes is [Apache-2.0](https://github.com/kubernetes/kubernetes?tab=Apache-2.0-1-ov-file#readme) licensed and that file isn't mentioned in the recipe so won't be included in the package anyway?

**Comment by AliPiccioniQC** [comment]
> Thanks for fixing the build! It looks good, but what's with the addition of the `recipe-scripts-license.txt` file?
> 
> Kubernetes is [Apache-2.0](https://github.com/kubernetes/kubernetes?tab=Apache-2.0-1-ov-file#readme) licensed and that file isn't mentioned in the recipe so won't be included in the package anyway?

Thanks for the feedback. I've gone ahead and removed that file. I'm not sure how it got in - I can see that LICENSE.txt gets copied to recipe/recipe-scripts-license.txt in several of the build scripts, this must have somehow leaked into my local git repo.

**Review by dhirschfeld — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
