### PR TITLE
Remove C compiler pinning

### PR DESCRIPTION
**Pull request by stepanhruda**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Simply removed pinning and re-rendered, expecting an environment failure on osx-64 and linux-64.

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
I think the errors here may be a different issue:
```
Detected go version: go version go1.13.5 linux/amd64.
Kubernetes requires go1.17.0 or greater.
Please install go1.17.0 or later.
```

The `go` pin was also removed in #101. For whatever reason it seemed to work there but not now :/

In any case, I think `go` can be pinned in a `conda_build_config.yaml` alongside the recipe - e.g.
https://github.com/conda-forge/podman-feedstock/blob/34438096050fff5111e5b3614a7980af5365ee11/recipe/conda_build_config.yaml

**Comment by dhirschfeld** [comment]
I took the liberty of adding that pin. We'll see how that works out...

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
This commit ( https://github.com/conda-forge/podman-feedstock/pull/15/commits/6512d814f4ea8c3f4b9c1ee51297b7ce6d37f06a ) looks relevant for [this CI failure]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=475500&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d )

<details>

```
Mamba failed to solve:
 - go-cgo_linux-64 1.17.*
 - gcc_linux-64 10.*
 - bash >=4.2
 - jq
 - make
 - rsync

with channels:

The reported errors are:
- Encountered problems while solving:
-   - package go-cgo_linux-64-1.17.6-hb09e268_1 requires _go_select ==2.3.0 cgo, but none of the providers can be installed
- 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 124, in mamba_get_install_actions
    solution = solver.solve_for_action(_specs, prefix)
  File "/opt/conda/lib/python3.9/site-packages/boa/core/solver.py", line 234, in solve_for_action
    t = self.solve(specs)
  File "/opt/conda/lib/python3.9/site-packages/boa/core/solver.py", line 216, in solve
    raise RuntimeError("Solver could not find solution." + error_string)
RuntimeError: Solver could not find solution.Mamba failed to solve:
 - go-cgo_linux-64 1.17.*
 - gcc_linux-64 10.*
 - bash >=4.2
 - jq
 - make
 - rsync
```

</details>

**Comment by jakirkham** [comment]
Would think `cgo` needs to be rebuilt with the new compilers. In fact that seems to have happened in PR ( https://github.com/conda-forge/go-feedstock/pull/140 ), but there are still some issues installing them. Probably the next thing to do is follow up on that feedstock showing the issues we've seen here

**Comment by dhirschfeld** [comment]
Resolved by #112

**Pull request closed without merging**
