### PR TITLE
Update to 1.15.1

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
OS-X Error:
```
conda.exceptions.ResolvePackageNotFound: 
  - go-cgo_osx-64=1.12
```

**Comment by dhirschfeld** [comment]
Maybe it's a heisenbug...
🤞

**Comment by sodre** [comment]
@dhirschfeld, we need to wait until https://github.com/conda-forge/go-feedstock/runs/186190392 this finishes building....

**Comment by dhirschfeld** [comment]
Thanks for the merge! 🚀

**Pull request merged**
