### PR TITLE
V1.15.0

### PR DESCRIPTION
**Pull request by agcopenhaver**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by agcopenhaver** [comment]
@conda-forge-admin, please rerender

**Comment by agcopenhaver** [comment]
Failing on osx because go v1.12 not available for osx

**Comment by sodre** [comment]
@conda-forge-admin, please rerender

**Comment by sodre** [comment]
@agcopenhaver, can you redo this PR. I would like to get 1.15.0 added as well, but I am not sure why it is failing on Linux while 1.15.1 and 1.15.2 worked..

**Comment by agcopenhaver** [comment]
@sodre I'm on it

**Comment by agcopenhaver** [comment]
@conda-forge-admin, please rerender

**Comment by agcopenhaver** [comment]
@conda-forge-admin, please rerender

**Comment by agcopenhaver** [comment]
@sodre should be g2g

**Comment by sodre** [comment]
Thanks @agcopenhaver

**Pull request merged**
