### PR TITLE
macOS arm64 support

### PR DESCRIPTION
**Pull request by stepanhruda**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

This is a re-issue of #100 with custom changes since I'm not allowed to push into that PR/branch.

* looks like updating C compiler version on macOS x86_64 and Linux fails resolving build environment, so pin it to current version now
* changes to build script since when cross-compiling, main repo Makefile puts output into a different directory

### CODE REVIEW

**Review by dhirschfeld — APPROVED** [review]

**Comment by jakirkham** [comment]
JFYI we updated to newer compiler versions here ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2010 ). So would be good to use them here and if there are issues figure out what they are

**Comment by stepanhruda** [comment]
@jakirkham I saw, but didn't want to conflate the issue that would happen during a simple rerender with adding new platform support. For some reason mamba fails to resolve the requirements, you can see the error in #100

**Comment by jakirkham** [comment]
Makes sene. Perhaps a new issue or PR demonstrating the issue would be a good next step?

**Comment by jakirkham** [comment]
Perfect thanks! 🙏

**Pull request merged**
